# Generated by Django 3.1.7 on 2021-03-31 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210330_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('wheel_type', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=100)),
                ('car_number', models.IntegerField(default=0)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dossier')),
            ],
        ),
    ]
